name: demo
recipe: wordpress
config:
  php: '8.0'
  composer_version: '2.0.7'
  via: apache:2.4
  webroot: .
  database: mysql:5.7
  xdebug: true

tooling:
  install:wordpress:
    service: appserver
    cmd:
      - wp core download && wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database
  
  install:sage:
    service: appserver
    cmd:
      - cd /app/wp-content/themes && read -p "What's the name of the theme? " theme && mkdir ${theme} && cd ${theme} && composer create-project roots/sage ${theme}
