name: demo
recipe: wordpress
config:
  php: '8.0'
  composer_version: '2.0.7'
  via: apache:2.4
  webroot: .
  database: mysql:5.7
  xdebug: true

services:
  node:
    type: node:16

tooling:
  add:wordpress:
    service: appserver
    cmd:
      - wp core download && wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database
   
  add:sage:
    service: appserver
    cmd:
      - cd /app/wp-content/themes && cd ${LANDO_APP_NAME} && composer create-project roots/sage ${LANDO_APP_NAME}

  install:sage:
    service: appserver
    cmd: 
      - cd /app/wp-content/themes/${LANDO_APP_NAME} && composer install

  install:plugins:
    service: appserver
    cmd: 
      - composer install

  build:
    service: node
    cmd: 
      - cd /app/wp-content/themes/${LANDO_APP_NAME} && npm i && npm run build
  
  watch:
    service: node
    cmd:
      - cd /app/wp-content/themes/${LANDO_APP_NAME} && npm run dev